platform :ios, '5.0'

pod 'SSToolkit', '1.0.2'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'Reachability'
pod 'MagicalRecord', '2.1'
pod 'SDWebImage'
pod 'ShareKit/Vkontakte'
pod 'ShareKit/Facebook'
pod 'ShareKit/Twitter'
pod 'MKStoreKit'